disabled_rules: # rule identifiers to exclude from running
  - todo
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300
# or they can set both explicitly
type_body_length:
  error: 1000
file_length:
  warning: 500
  error: 1600
identifier_name:
  min_length: # only min_length
    error: 2
  excluded: # excluded via string array
    - id
    - vc
